export const state = {
  currentView: "assess",
  diagnosisSessions: [],
  activeSessionId: null,
  allControls: [],
  checklist: [],
  assessments: {},
  controlChecks: {},
  controlEvidence: {},
  domainChecks: {},
  domainTouched: {},
  analysis: null,
  analysisHistory: [],
  analysisStale: false,
  lastAiExecutiveReport: null,
  aiReportStale: false,
  aiReportWriting: false,
  reportReview: {},
  reportReturn: null,
  dashboard: null,
  areaFilter: "all",
  levelFilter: "all",
  assessSearch: "",
  expandedRows: new Set(),
  collapsedCategories: new Set(),
  activeCategoryId: null,
  categoriesBootstrapped: false,
  analyzeSection: "actions",
  analyzeDetailTab: "problem",
  cascadeExpanded: false,
  problemFiltersOpen: false,
  detailReturnContext: null,
  expandedGapInline: {},
  expandedProblemCascade: new Set(),
  expandedProblemGroups: new Set(),
  expandedProblemItems: new Set(),
  problemAreaFilter: "all",
  problemLevelFilter: "all",
  problemSeverityFilter: "all",
  problemSourceFilter: "all",
  problemChecklistQuery: "",
  problemViewMode: "all", // all | individual | compound
  selectedProblemCategory: null,
  selectedProblemControl: null,
  multigapSeverityFilter: "all",
  selectedMultigapTheme: null,
  expandedMultigapThemes: new Set(),
  gapSearch: "",
  gapLevelFilter: "all",
  expandedGaps: new Set(),
  expandedMultigaps: new Set(),
  expandedProblemClusters: new Set(),
  gapRevealPending: false,
  analyzeScenarioId: null,
  sessionBundleMode: "chain",
  sessionSelectedControlId: null,
  pendingDoneEvidenceControlId: null,
  sessionCollapsedCategories: new Set(),
  organizationProfile: null,
  pendingProfile: null,
  scopeDraft: null,
  questChecks: {},
  inputConfidence: {},
  legalBasisCache: {},
};
